### ISSUE TITLE
Issue with Disqus?

### ISSUE THREAD

**Issue by riklopfer** [digitalcraftsman/hugo-steam-theme#14]
The Disqus comments section takes forever to load. I have `disqusShortname` set in my `config.toml` but I am now commenting that out to avoid the issue. 

Hugo version: Hugo Static Site Generator v0.17 BuildDate: 2016-10-07T10:46:29-04:00

**Comment by digitalcraftsman** [comment]
Hello @riklopfer,

> The Disqus comments section takes forever to load

about what timespan are talking?

**Comment by riklopfer** [comment]
> about what timespan are talking?
Several minutes. I suppose it could have been an issue with Disqus. If you cannot reproduce the issue, feel free to close. I wanted to log the report in case there were a "real" issue.

**Comment by digitalcraftsman** [comment]
I tried it locally and and with the demo on the theme site. On both cases the comment section appeared immediately. But several minutes aren't normal. Could it be possible that some browser extensions try prevent that files from Disqus are fetched?

It might be worth to have a look at the console in the developer tools of your browser (F12 -> console tab). Do you see any error messages?

**Comment by digitalcraftsman** [comment]
This issue seems to be stale so I'm closing it. Feel free to reopen it if the issue is still relevant.
