### ISSUE TITLE
Disqus support not working

### ISSUE THREAD

**Issue by eljobe** [digitalcraftsman/hugo-steam-theme#22]
My simple site built with this theme doesn't render a Disqus section for blog posts.

This [line](https://github.com/digitalcraftsman/hugo-steam-theme/blob/master/layouts/_default/single.html#L27) suggests that a templated called "_internal/disqus.html" should be rendered, but I don't see that template at all. Am I expected to provide it as a user of the theme?

**Comment by digitalcraftsman** [comment]
Hello @eljobe,

you as a user are not exptected to provide this template. Hugo [ships a few built-in templates](https://gohugo.io/templates/internal/#disqus) (hence the `_internal` in the path) for common usecases like the integration of Disqus.

Please make sure that `disqusShortname` has been set in the config with your Disqus shortname and that you setup Disqus accordingly.

**Comment by eljobe** [comment]
I finally figured that out. It looks like I needed to upgrade my version of hugo to the the disqus functionality. It's probably a good idea to mention a minimum hugo version in your documentation. (Sorry in advance if it's there and I missed it.)

Anyway. I got it working. Thanks.

**Comment by digitalcraftsman** [comment]
That's great. Which version of Hugo were you using? 
Btw, you can find the metadata of a theme, including the minimal required version of Hugo, in [`theme.toml`](https://github.com/digitalcraftsman/hugo-steam-theme/blob/master/theme.toml).

**Comment by eljobe** [comment]
I was using 2.1. But, I actually found the "real" problem was that I had named my `post` directory `posts` so this check was failing. https://github.com/digitalcraftsman/hugo-steam-theme/blob/master/layouts/_default/single.html#L16

**Comment by digitalcraftsman** [comment]
Checking for the post type is a bit limiting for the user. I should improve template code in this area.
